language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ~/.m2/repository
script:
- mvn clean package
after_success:
- openssl aes-256-cbc -K $encrypted_6a0be8cfd9ec_key -iv $encrypted_6a0be8cfd9ec_iv -in key.asc.enc -out key.asc -d && gpg --fast-import key.asc
- mvn clean deploy -DskipTests --settings settings.xml -Pdeploy